//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace French_Fri_Clicker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friSave1 {
            get {
                return ((long)(this["friSave1"]));
            }
            set {
                this["friSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long fpsSave1 {
            get {
                return ((long)(this["fpsSave1"]));
            }
            set {
                this["fpsSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long fpcSave1 {
            get {
                return ((long)(this["fpcSave1"]));
            }
            set {
                this["fpcSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long cheatsonSave1 {
            get {
                return ((long)(this["cheatsonSave1"]));
            }
            set {
                this["cheatsonSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricePotatopotSave1 {
            get {
                return ((long)(this["incpricePotatopotSave1"]));
            }
            set {
                this["incpricePotatopotSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceSmallfarmSave1 {
            get {
                return ((long)(this["incpriceSmallfarmSave1"]));
            }
            set {
                this["incpriceSmallfarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceGreenhouseSave1 {
            get {
                return ((long)(this["incpriceGreenhouseSave1"]));
            }
            set {
                this["incpriceGreenhouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceFarmSave1 {
            get {
                return ((long)(this["incpriceFarmSave1"]));
            }
            set {
                this["incpriceFarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceBoxoSave1 {
            get {
                return ((long)(this["incpriceBoxoSave1"]));
            }
            set {
                this["incpriceBoxoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceSackoSave1 {
            get {
                return ((long)(this["incpriceSackoSave1"]));
            }
            set {
                this["incpriceSackoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricePotatocrateSave1 {
            get {
                return ((long)(this["incpricePotatocrateSave1"]));
            }
            set {
                this["incpricePotatocrateSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceShippingboatSave1 {
            get {
                return ((long)(this["incpriceShippingboatSave1"]));
            }
            set {
                this["incpriceShippingboatSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceHandpotatocutterSave1 {
            get {
                return ((long)(this["incpriceHandpotatocutterSave1"]));
            }
            set {
                this["incpriceHandpotatocutterSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceDeepfryerSave1 {
            get {
                return ((long)(this["incpriceDeepfryerSave1"]));
            }
            set {
                this["incpriceDeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceOvenfriesSave1 {
            get {
                return ((long)(this["incpriceOvenfriesSave1"]));
            }
            set {
                this["incpriceOvenfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceSmallfriesSave1 {
            get {
                return ((long)(this["incpriceSmallfriesSave1"]));
            }
            set {
                this["incpriceSmallfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceFrenchFriSave1 {
            get {
                return ((long)(this["incpriceFrenchFriSave1"]));
            }
            set {
                this["incpriceFrenchFriSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricebagofriesSave1 {
            get {
                return ((long)(this["incpricebagofriesSave1"]));
            }
            set {
                this["incpricebagofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricelargedeepfryerSave1 {
            get {
                return ((long)(this["incpricelargedeepfryerSave1"]));
            }
            set {
                this["incpricelargedeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricebarrelofriesSave1 {
            get {
                return ((long)(this["incpricebarrelofriesSave1"]));
            }
            set {
                this["incpricebarrelofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceThefritruckSave1 {
            get {
                return ((long)(this["incpriceThefritruckSave1"]));
            }
            set {
                this["incpriceThefritruckSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricefrenchfriplaneSave1 {
            get {
                return ((long)(this["incpricefrenchfriplaneSave1"]));
            }
            set {
                this["incpricefrenchfriplaneSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceGiantpotatosiloSave1 {
            get {
                return ((long)(this["incpriceGiantpotatosiloSave1"]));
            }
            set {
                this["incpriceGiantpotatosiloSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricePotatoblimpSave1 {
            get {
                return ((long)(this["incpricePotatoblimpSave1"]));
            }
            set {
                this["incpricePotatoblimpSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpricePotatofactorySave1 {
            get {
                return ((long)(this["incpricePotatofactorySave1"]));
            }
            set {
                this["incpricePotatofactorySave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceFrenchfriStandSave1 {
            get {
                return ((long)(this["incpriceFrenchfriStandSave1"]));
            }
            set {
                this["incpriceFrenchfriStandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceFrenchfritrainSave1 {
            get {
                return ((long)(this["incpriceFrenchfritrainSave1"]));
            }
            set {
                this["incpriceFrenchfritrainSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incpriceFrenchfriknifeSave1 {
            get {
                return ((long)(this["incpriceFrenchfriknifeSave1"]));
            }
            set {
                this["incpriceFrenchfriknifeSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatopotSave1 {
            get {
                return ((long)(this["amtPotatopotSave1"]));
            }
            set {
                this["amtPotatopotSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtSmallfarmSave1 {
            get {
                return ((long)(this["amtSmallfarmSave1"]));
            }
            set {
                this["amtSmallfarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtGreenhouseSave1 {
            get {
                return ((long)(this["amtGreenhouseSave1"]));
            }
            set {
                this["amtGreenhouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtFarmSave1 {
            get {
                return ((long)(this["amtFarmSave1"]));
            }
            set {
                this["amtFarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtBoxpotatoSave1 {
            get {
                return ((long)(this["amtBoxpotatoSave1"]));
            }
            set {
                this["amtBoxpotatoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtSackopotatoSave1 {
            get {
                return ((long)(this["amtSackopotatoSave1"]));
            }
            set {
                this["amtSackopotatoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatocrateSave1 {
            get {
                return ((long)(this["amtPotatocrateSave1"]));
            }
            set {
                this["amtPotatocrateSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatoshippingcrateSave1 {
            get {
                return ((long)(this["amtPotatoshippingcrateSave1"]));
            }
            set {
                this["amtPotatoshippingcrateSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtHandPotatocutterSave1 {
            get {
                return ((long)(this["amtHandPotatocutterSave1"]));
            }
            set {
                this["amtHandPotatocutterSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtDeepfryerSave1 {
            get {
                return ((long)(this["amtDeepfryerSave1"]));
            }
            set {
                this["amtDeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtOvenfriesSave1 {
            get {
                return ((long)(this["amtOvenfriesSave1"]));
            }
            set {
                this["amtOvenfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtSmallfriesSave1 {
            get {
                return ((long)(this["amtSmallfriesSave1"]));
            }
            set {
                this["amtSmallfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtFrenchFriSave1 {
            get {
                return ((long)(this["amtFrenchFriSave1"]));
            }
            set {
                this["amtFrenchFriSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtbagofriesSave1 {
            get {
                return ((long)(this["amtbagofriesSave1"]));
            }
            set {
                this["amtbagofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtlargedeepfryerSave1 {
            get {
                return ((long)(this["amtlargedeepfryerSave1"]));
            }
            set {
                this["amtlargedeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtbarrelofriesSave1 {
            get {
                return ((long)(this["amtbarrelofriesSave1"]));
            }
            set {
                this["amtbarrelofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtThefritruckSave1 {
            get {
                return ((long)(this["amtThefritruckSave1"]));
            }
            set {
                this["amtThefritruckSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtfrenchfriplaneSave1 {
            get {
                return ((long)(this["amtfrenchfriplaneSave1"]));
            }
            set {
                this["amtfrenchfriplaneSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtGiantpotatosiloSave1 {
            get {
                return ((long)(this["amtGiantpotatosiloSave1"]));
            }
            set {
                this["amtGiantpotatosiloSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatoblimpSave1 {
            get {
                return ((long)(this["amtPotatoblimpSave1"]));
            }
            set {
                this["amtPotatoblimpSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatofactorySave1 {
            get {
                return ((long)(this["amtPotatofactorySave1"]));
            }
            set {
                this["amtPotatofactorySave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtFrenchfriStandSave1 {
            get {
                return ((long)(this["amtFrenchfriStandSave1"]));
            }
            set {
                this["amtFrenchfriStandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtFrenchfritrainSave1 {
            get {
                return ((long)(this["amtFrenchfritrainSave1"]));
            }
            set {
                this["amtFrenchfritrainSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtFrenchfriknifeSave1 {
            get {
                return ((long)(this["amtFrenchfriknifeSave1"]));
            }
            set {
                this["amtFrenchfriknifeSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friFarmSave1 {
            get {
                return ((long)(this["friFarmSave1"]));
            }
            set {
                this["friFarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friBoxopotatoSave1 {
            get {
                return ((long)(this["friBoxopotatoSave1"]));
            }
            set {
                this["friBoxopotatoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friSackopotatoSave1 {
            get {
                return ((long)(this["friSackopotatoSave1"]));
            }
            set {
                this["friSackopotatoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friPotatocrateSave1 {
            get {
                return ((long)(this["friPotatocrateSave1"]));
            }
            set {
                this["friPotatocrateSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friPotatoshippingboatSave1 {
            get {
                return ((long)(this["friPotatoshippingboatSave1"]));
            }
            set {
                this["friPotatoshippingboatSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friHandpotatocutterSave1 {
            get {
                return ((long)(this["friHandpotatocutterSave1"]));
            }
            set {
                this["friHandpotatocutterSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friDeepfryerSave1 {
            get {
                return ((long)(this["friDeepfryerSave1"]));
            }
            set {
                this["friDeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friOvenfriesSave1 {
            get {
                return ((long)(this["friOvenfriesSave1"]));
            }
            set {
                this["friOvenfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friSmallfriesSave1 {
            get {
                return ((long)(this["friSmallfriesSave1"]));
            }
            set {
                this["friSmallfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friFrenchFriSave1 {
            get {
                return ((long)(this["friFrenchFriSave1"]));
            }
            set {
                this["friFrenchFriSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long fribagofriesSave1 {
            get {
                return ((long)(this["fribagofriesSave1"]));
            }
            set {
                this["fribagofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long frilargedeepfryerSave1 {
            get {
                return ((long)(this["frilargedeepfryerSave1"]));
            }
            set {
                this["frilargedeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long fribarrelofriesSave1 {
            get {
                return ((long)(this["fribarrelofriesSave1"]));
            }
            set {
                this["fribarrelofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friThefritruckSave1 {
            get {
                return ((long)(this["friThefritruckSave1"]));
            }
            set {
                this["friThefritruckSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long frifrenchfriplaneSave1 {
            get {
                return ((long)(this["frifrenchfriplaneSave1"]));
            }
            set {
                this["frifrenchfriplaneSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friGiantpotatosiloSave1 {
            get {
                return ((long)(this["friGiantpotatosiloSave1"]));
            }
            set {
                this["friGiantpotatosiloSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friPotatoblimpSave1 {
            get {
                return ((long)(this["friPotatoblimpSave1"]));
            }
            set {
                this["friPotatoblimpSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friPotatofactorySave1 {
            get {
                return ((long)(this["friPotatofactorySave1"]));
            }
            set {
                this["friPotatofactorySave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friFrenchfriStandSave1 {
            get {
                return ((long)(this["friFrenchfriStandSave1"]));
            }
            set {
                this["friFrenchfriStandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friFrenchfritrainSave1 {
            get {
                return ((long)(this["friFrenchfritrainSave1"]));
            }
            set {
                this["friFrenchfritrainSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long friFrenchfriknifeSave1 {
            get {
                return ((long)(this["friFrenchfriknifeSave1"]));
            }
            set {
                this["friFrenchfriknifeSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricePotatopotSave1 {
            get {
                return ((long)(this["pricePotatopotSave1"]));
            }
            set {
                this["pricePotatopotSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceSmallfarmSave1 {
            get {
                return ((long)(this["priceSmallfarmSave1"]));
            }
            set {
                this["priceSmallfarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceGreenhouseSave1 {
            get {
                return ((long)(this["priceGreenhouseSave1"]));
            }
            set {
                this["priceGreenhouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceFarmSave1 {
            get {
                return ((long)(this["priceFarmSave1"]));
            }
            set {
                this["priceFarmSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceBoxopotatoSave1 {
            get {
                return ((long)(this["priceBoxopotatoSave1"]));
            }
            set {
                this["priceBoxopotatoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceSackopotatoSave1 {
            get {
                return ((long)(this["priceSackopotatoSave1"]));
            }
            set {
                this["priceSackopotatoSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricePotatocrateSave1 {
            get {
                return ((long)(this["pricePotatocrateSave1"]));
            }
            set {
                this["pricePotatocrateSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricePotatoshippingboatSave1 {
            get {
                return ((long)(this["pricePotatoshippingboatSave1"]));
            }
            set {
                this["pricePotatoshippingboatSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricehandpotatocutterSave1 {
            get {
                return ((long)(this["pricehandpotatocutterSave1"]));
            }
            set {
                this["pricehandpotatocutterSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricedeepfryerSave1 {
            get {
                return ((long)(this["pricedeepfryerSave1"]));
            }
            set {
                this["pricedeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceovenfriesSave1 {
            get {
                return ((long)(this["priceovenfriesSave1"]));
            }
            set {
                this["priceovenfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricesmallfriesSave1 {
            get {
                return ((long)(this["pricesmallfriesSave1"]));
            }
            set {
                this["pricesmallfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceFrenchfriesSave1 {
            get {
                return ((long)(this["priceFrenchfriesSave1"]));
            }
            set {
                this["priceFrenchfriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceBagofriesSave1 {
            get {
                return ((long)(this["priceBagofriesSave1"]));
            }
            set {
                this["priceBagofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceLargedeepfryerSave1 {
            get {
                return ((long)(this["priceLargedeepfryerSave1"]));
            }
            set {
                this["priceLargedeepfryerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceBarrelofriesSave1 {
            get {
                return ((long)(this["priceBarrelofriesSave1"]));
            }
            set {
                this["priceBarrelofriesSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceThefritruckSave1 {
            get {
                return ((long)(this["priceThefritruckSave1"]));
            }
            set {
                this["priceThefritruckSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceFrenchfriplaneSave1 {
            get {
                return ((long)(this["priceFrenchfriplaneSave1"]));
            }
            set {
                this["priceFrenchfriplaneSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceGiantpotatosiloSave1 {
            get {
                return ((long)(this["priceGiantpotatosiloSave1"]));
            }
            set {
                this["priceGiantpotatosiloSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricePotatoblimpSave1 {
            get {
                return ((long)(this["pricePotatoblimpSave1"]));
            }
            set {
                this["pricePotatoblimpSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long pricePotatofactorySave1 {
            get {
                return ((long)(this["pricePotatofactorySave1"]));
            }
            set {
                this["pricePotatofactorySave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceFrenchfriStandSave1 {
            get {
                return ((long)(this["priceFrenchfriStandSave1"]));
            }
            set {
                this["priceFrenchfriStandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceFrenchfritrainSave1 {
            get {
                return ((long)(this["priceFrenchfritrainSave1"]));
            }
            set {
                this["priceFrenchfritrainSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceFrenchfriknifeSave1 {
            get {
                return ((long)(this["priceFrenchfriknifeSave1"]));
            }
            set {
                this["priceFrenchfriknifeSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtBasicclickerSave1 {
            get {
                return ((long)(this["amtBasicclickerSave1"]));
            }
            set {
                this["amtBasicclickerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatoclickerSave1 {
            get {
                return ((long)(this["amtPotatoclickerSave1"]));
            }
            set {
                this["amtPotatoclickerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatohelperSave1 {
            get {
                return ((long)(this["amtPotatohelperSave1"]));
            }
            set {
                this["amtPotatohelperSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtDellmouseSave1 {
            get {
                return ((long)(this["amtDellmouseSave1"]));
            }
            set {
                this["amtDellmouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtRazermouseSave1 {
            get {
                return ((long)(this["amtRazermouseSave1"]));
            }
            set {
                this["amtRazermouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amt15DollarmouseSave1 {
            get {
                return ((long)(this["amt15DollarmouseSave1"]));
            }
            set {
                this["amt15DollarmouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPotatoMouseSave1 {
            get {
                return ((long)(this["amtPotatoMouseSave1"]));
            }
            set {
                this["amtPotatoMouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtSparehandSave1 {
            get {
                return ((long)(this["amtSparehandSave1"]));
            }
            set {
                this["amtSparehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtBronzehandSave1 {
            get {
                return ((long)(this["amtBronzehandSave1"]));
            }
            set {
                this["amtBronzehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtSilverhandSave1 {
            get {
                return ((long)(this["amtSilverhandSave1"]));
            }
            set {
                this["amtSilverhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtGoldhandSave1 {
            get {
                return ((long)(this["amtGoldhandSave1"]));
            }
            set {
                this["amtGoldhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtPlatinumhandSave1 {
            get {
                return ((long)(this["amtPlatinumhandSave1"]));
            }
            set {
                this["amtPlatinumhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtAmythysthandSave1 {
            get {
                return ((long)(this["amtAmythysthandSave1"]));
            }
            set {
                this["amtAmythysthandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtTopazhandSave1 {
            get {
                return ((long)(this["amtTopazhandSave1"]));
            }
            set {
                this["amtTopazhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtRubyhandSave1 {
            get {
                return ((long)(this["amtRubyhandSave1"]));
            }
            set {
                this["amtRubyhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long amtSapphirehandSave1 {
            get {
                return ((long)(this["amtSapphirehandSave1"]));
            }
            set {
                this["amtSapphirehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofBasicclickerSave1 {
            get {
                return ((long)(this["priceofBasicclickerSave1"]));
            }
            set {
                this["priceofBasicclickerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofPotatoclcikerSave1 {
            get {
                return ((long)(this["priceofPotatoclcikerSave1"]));
            }
            set {
                this["priceofPotatoclcikerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofPotatohelperSave1 {
            get {
                return ((long)(this["priceofPotatohelperSave1"]));
            }
            set {
                this["priceofPotatohelperSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofDellmouseSave1 {
            get {
                return ((long)(this["priceofDellmouseSave1"]));
            }
            set {
                this["priceofDellmouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofRazermouseSave1 {
            get {
                return ((long)(this["priceofRazermouseSave1"]));
            }
            set {
                this["priceofRazermouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceof15DollarmouseSave1 {
            get {
                return ((long)(this["priceof15DollarmouseSave1"]));
            }
            set {
                this["priceof15DollarmouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofPotatoMouseSave1 {
            get {
                return ((long)(this["priceofPotatoMouseSave1"]));
            }
            set {
                this["priceofPotatoMouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofSparehandSave1 {
            get {
                return ((long)(this["priceofSparehandSave1"]));
            }
            set {
                this["priceofSparehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofBronzehandSave1 {
            get {
                return ((long)(this["priceofBronzehandSave1"]));
            }
            set {
                this["priceofBronzehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofSilverhandSave1 {
            get {
                return ((long)(this["priceofSilverhandSave1"]));
            }
            set {
                this["priceofSilverhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofGoldhandSave1 {
            get {
                return ((long)(this["priceofGoldhandSave1"]));
            }
            set {
                this["priceofGoldhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofPlatinumhandSave1 {
            get {
                return ((long)(this["priceofPlatinumhandSave1"]));
            }
            set {
                this["priceofPlatinumhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofAmythysthandSave1 {
            get {
                return ((long)(this["priceofAmythysthandSave1"]));
            }
            set {
                this["priceofAmythysthandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofTopazhandSave1 {
            get {
                return ((long)(this["priceofTopazhandSave1"]));
            }
            set {
                this["priceofTopazhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofRubyhandSave1 {
            get {
                return ((long)(this["priceofRubyhandSave1"]));
            }
            set {
                this["priceofRubyhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long priceofSapphirehandSave1 {
            get {
                return ((long)(this["priceofSapphirehandSave1"]));
            }
            set {
                this["priceofSapphirehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incBasicclickerSave1 {
            get {
                return ((long)(this["incBasicclickerSave1"]));
            }
            set {
                this["incBasicclickerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incPotatoclickerSave1 {
            get {
                return ((long)(this["incPotatoclickerSave1"]));
            }
            set {
                this["incPotatoclickerSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incPotatohelperSave1 {
            get {
                return ((long)(this["incPotatohelperSave1"]));
            }
            set {
                this["incPotatohelperSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incDellmouseSave1 {
            get {
                return ((long)(this["incDellmouseSave1"]));
            }
            set {
                this["incDellmouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incRazermouseSave1 {
            get {
                return ((long)(this["incRazermouseSave1"]));
            }
            set {
                this["incRazermouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long inc15DollarmouseSave1 {
            get {
                return ((long)(this["inc15DollarmouseSave1"]));
            }
            set {
                this["inc15DollarmouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incPotatoMouseSave1 {
            get {
                return ((long)(this["incPotatoMouseSave1"]));
            }
            set {
                this["incPotatoMouseSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incSparehandSave1 {
            get {
                return ((long)(this["incSparehandSave1"]));
            }
            set {
                this["incSparehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incBronzehandSave1 {
            get {
                return ((long)(this["incBronzehandSave1"]));
            }
            set {
                this["incBronzehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incSilverhandSave1 {
            get {
                return ((long)(this["incSilverhandSave1"]));
            }
            set {
                this["incSilverhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incGoldhandSave1 {
            get {
                return ((long)(this["incGoldhandSave1"]));
            }
            set {
                this["incGoldhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incPlatinumhandSave1 {
            get {
                return ((long)(this["incPlatinumhandSave1"]));
            }
            set {
                this["incPlatinumhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incAmythysthandSave1 {
            get {
                return ((long)(this["incAmythysthandSave1"]));
            }
            set {
                this["incAmythysthandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incTopazhandSave1 {
            get {
                return ((long)(this["incTopazhandSave1"]));
            }
            set {
                this["incTopazhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incRubyhandSave1 {
            get {
                return ((long)(this["incRubyhandSave1"]));
            }
            set {
                this["incRubyhandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long incSapphirehandSave1 {
            get {
                return ((long)(this["incSapphirehandSave1"]));
            }
            set {
                this["incSapphirehandSave1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No Save")]
        public string Lasttime {
            get {
                return ((string)(this["Lasttime"]));
            }
            set {
                this["Lasttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long saveornoSave1 {
            get {
                return ((long)(this["saveornoSave1"]));
            }
            set {
                this["saveornoSave1"] = value;
            }
        }
    }
}
